---
# tasks file for hostname
- name: Install the correct web server for Ubuntu
  ansible.builtin.file:
    path: /bar.conf
    state: touch
    mode: u=rw,g=r,o=r
  tags: mytag

- name: Install the bar2 for Ubuntu
  ansible.builtin.file:
    path: /bar2.conf
    state: touch
    mode: u=rw,g=r,o=r
  tags: typeA