- name: Install Airflow
  hosts: centos
  gather_facts: true
  become: yes
  become_user: john

  vars:
    distribution: 'CentOS'

  tasks:
    - name: Test
      debug:
        msg: "{{ airflow_rabbitmq_port }}"
#    - name: Install Airflow via Role
#      import_role:
#        name: airflow
    - name: Debug message
      ansible.builtin.debug:
        msg: '{{ distribution }}'