- name: App Server
  gather_facts: false
  hosts: centos
  become: true

  tasks:
#  - name: Setup NTP
#    include_role:
#      name: centos_ntp
  - name: install pip3
    yum:
      name: python3-pip
      state: present
  - name: install pip
    yum:
      name: python-pip
      state: present
  - name: Install django
    pip:
      name: django
      executable: pip3
  - name: create admin group
    group:
      name: admin
      state: present
  - name: create new user & add ssh key
    user:
      name: john
      group: admin
      createhome: yes
      generate_ssh_key: yes
      password: "{{ 'john' | password_hash('sha512') }}"
  - name: Install git
    package:
      name: git
      state: present
  - name: Copy file to server
    copy:
      src=/etc/hosts
      dest=/tmp/hosts
  - name: Fetch file from server
    fetch:
      src: /etc/hosts
      dest: /tmp
  - name: create directory
    file:
      dest: /tmp/test
      mode: 644
      state: directory
  - name: create a symlink
    file:
      src: /tmp/test
      dest: /tmp/test2
      state: link
#      other file management tools: lineinfile, ini_file, unarchive