- name: Update web servers
  hosts: string
  remote_user: root

  tasks:
  - name: Touch file with hostname role
    include_role:
      name: hostname
  - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
    ansible.builtin.file:
      path: /etc/foo.conf
      state: touch
      mode: u=rw,g=r,o=r
  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /etc/some_directory
      state: directory
      mode: '0755'