- name: Update web servers
  gather_facts: false
  hosts: string
  become: yes

  tasks:
  - name: Touch file with hostname role
    include_role:
      name: hostname
    vars:
      dir: '/opt/a'
    tags: typeA
  - name: Setup NTP
    include_role:
      name: ntp
  - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
    ansible.builtin.file:
      path: /etc/foo.conf
      state: touch
      mode: u=rw,g=r,o=r
  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /etc/some_directory
      state: directory
      mode: '0755'