- name: Update web servers
  gather_facts: false
  hosts: leafs
  become: yes

  tasks:
#  - name: Touch file with hostname role
#    include_role:
#      name: hostname
#    vars:
#      dir: '/opt/a'
#    tags: typeA
  - name: After version 2.7 both 'msg' and 'fail_msg' can customize failing assertion message
    ansible.builtin.assert:
      that:
        - my_param <= 100
        - my_param >= 0
      fail_msg: "'my_param' must be between 0 and 100"
      success_msg: "'my_param' is between 0 and 100"
    run_once: true
  - name: Check required variable
    assert:
      fail_msg: failfejfei
#      success_msg: passed
#      quiet: true
      that:
        - airflow_fernet_key | string is defined
    run_once: true
  - name: Setup NTP
    include_role:
      name: ntp
  - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
    ansible.builtin.file:
      path: /etc/foo.conf
      state: touch
      mode: u=rw,g=r,o=r
  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /etc/some_directory
      state: directory
      mode: '0755'
